[sdk]
image = "ghcr.io/avocado-framework/avocado-sdk:latest"

[runtime.default]
target = "aarch64-unknown-linux-gnu"

[ext.custom-app]
types = ["sysext"]
packages = ["curl"]
version = "1.5.0"
arch = "noarch"
