default_target = "reterminal-dm"

# Add additional supported targets or use "*" for all targets
supported_targets = ["reterminal-dm"]

##
## Runtimes
##

[runtime.dev.dependencies]
avocado-img-bootfiles = "*"
avocado-img-rootfs = "*"
avocado-img-initramfs = "*"
avocado-ext-dev = { ext = "avocado-ext-dev", vsn = "*" }
avocado-ext-sshd-dev = { ext = "avocado-ext-sshd-dev", vsn = "*" }
config = { ext = "config" }
app = { ext = "app" }

##
## Extensions
##

# Generated default app extension
# Use or modify this to install dependencies and or include sdk compiled code
[ext.app]
types = ["sysext", "confext"]

# Install application dependencies
[ext.app.dependencies]
#curl = "*"
#iperf3 = "*"

# Generated default config extension
# Use or modify this to configure "real" user accounts (passwd, shadow, group)
# or configure other system services
[ext.config]
types = ["confext"]

# NOT FOR PRODUCTION: Set root password to empty string
[ext.config.users.root]
password = ""

##
## SDK
##

[sdk]
image = "docker.io/avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
avocado-sdk-toolchain = "*"

[sdk.reterminal-dm]
container_args = ["--network=host"]

##
## Provisioning
##

[provision.usb]
container_args = ["-v", "/dev:/dev", "-v", "/sys:/sys:ro", "--privileged"]

[provision.sd]
container_args = ["-v", "/dev:/dev", "-v", "/sys:/sys:ro", "--privileged"]
