[sdk]
image = "ghcr.io/avocado-framework/avocado-sdk:latest"

[runtime.default]
target = "x86_64-unknown-linux-gnu"

[ext.avocado-dev]
types = ["sysext", "confext"]
packages = ["vim", "curl", "nginx", "postgresql"]

# Mixed approach for users: inline for simple, table syntax for complex
[ext.avocado-dev.users]
# Simple users with minimal configuration use inline syntax
root = { password = "" }
guest = { password = "*" }  # No login allowed

# Complex user with full passwd attributes
[ext.avocado-dev.users.alice]
password = "$6$salt$hash"
uid = 1001
gid = 1001
gecos = "Alice Smith,Engineering,Room 123,555-1234,555-5678"
home = "/home/alice"
shell = "/bin/zsh"
groups = ["users", "developers", "sudo"]

# User with comprehensive shadow attributes for password aging
[ext.avocado-dev.users.bob]
password = "$6$anothersalt$anotherhash"
uid = 1002
gecos = "Bob Johnson,DevOps Team"
home = "/home/bob"
shell = "/bin/bash"
groups = ["users", "admins"]
# Shadow file attributes for strict password policy
last_change = 19000     # Days since epoch when password was last changed
min_days = 7            # Minimum days between password changes
max_days = 90           # Maximum days before password expires
warn_days = 7           # Days before expiration to warn user
inactive_days = 14      # Days after expiration before account is disabled
expire_date = 20000     # Days since epoch when account expires

# System service user with specific configuration
[ext.avocado-dev.users.nginx]
password = "*"          # No login allowed
uid = 33
gid = 33
gecos = "nginx web server"
home = "/var/www"
shell = "/usr/sbin/nologin"
system = true           # Mark as system user

# Database service user
[ext.avocado-dev.users.postgres]
password = "!"          # Locked password
uid = 26
gid = 26
gecos = "PostgreSQL Server"
home = "/var/lib/pgsql"
shell = "/bin/bash"
system = true
groups = ["postgres"]

# Locked/disabled user account
[ext.avocado-dev.users.temp]
password = "!"
uid = 1099
disabled = true         # Account disabled
gecos = "Temporary disabled account"
groups = ["users"]

# Groups with mixed syntax
[ext.avocado-dev.groups]
# Simple groups use inline syntax
users = { gid = 1000 }
sudo = { gid = 27 }

# Complex group with members and password
[ext.avocado-dev.groups.developers]
gid = 2000
members = ["alice", "bob"]
system = false

# System group with administrative access
[ext.avocado-dev.groups.admins]
gid = 2001
system = true
members = ["bob"]

# Group with password for newgrp command
[ext.avocado-dev.groups.secure]
gid = 3000
password = "$6$groupsalt$grouphash"  # Group password for newgrp
admins = ["alice", "bob"]            # Group administrators
members = ["alice"]

# Service-specific groups
[ext.avocado-dev.groups.nginx]
gid = 33
system = true

[ext.avocado-dev.groups.postgres]
gid = 26
system = true
